/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilities.Exceptions;

/**
 *
 * @author carmen
 */
public class DiagnosisView extends javax.swing.JFrame {

    /**
     * Creates new form DiagnosisView
     */
    public DiagnosisView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        if (!DoctorInsideWindow.patient.getDiagnosis().equals("null")) {
            String[] datos = Exceptions.takeDiagnosis(DoctorInsideWindow.patient.getDiagnosis());
            this.diz.setText("Dizziness: " + datos[0]);
            this.syn.setText("Syncope: " + datos[1]);
            this.fat.setText("Fatigue: " + datos[2]);
            this.car.setText("Previous Cardiac dissease: " + datos[3]);
            this.con.setText("Condusion: " + datos[4]);
            this.obs.setText("Observations: " + datos[5]);
        } else {
            this.diag.setText("No diagnosis entered yet");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diz = new javax.swing.JLabel();
        syn = new javax.swing.JLabel();
        fat = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        con = new javax.swing.JLabel();
        obs = new javax.swing.JLabel();
        diag = new javax.swing.JLabel();
        backBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        diz.setText("Dizziness: ");

        syn.setText("Syncope:");

        fat.setText("Fatigue:");

        car.setText("Previous cardiac failure: ");

        con.setText("Confusion: ");

        obs.setText("Observations: ");

        diag.setText("Diagnosis:");

        backBut.setText("Back");
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(diag)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(obs)
                                .addComponent(con)
                                .addComponent(car)
                                .addComponent(fat)
                                .addComponent(syn)
                                .addComponent(diz))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backBut)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(diag)
                .addGap(18, 18, 18)
                .addComponent(diz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(syn)
                .addGap(18, 18, 18)
                .addComponent(fat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(car)
                .addGap(18, 18, 18)
                .addComponent(con)
                .addGap(18, 18, 18)
                .addComponent(obs)
                .addGap(18, 18, 18)
                .addComponent(backBut)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
        DataPatientWindow rd = new DataPatientWindow();
        this.setVisible(false);
        rd.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_backButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagnosisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagnosisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagnosisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagnosisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiagnosisView().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBut;
    private javax.swing.JLabel car;
    private javax.swing.JLabel con;
    private javax.swing.JLabel diag;
    private javax.swing.JLabel diz;
    private javax.swing.JLabel fat;
    private javax.swing.JLabel obs;
    private javax.swing.JLabel syn;
    // End of variables declaration//GEN-END:variables
}
