/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Pojos.Patient;
import Utilities.ConnectionWithServer;
import java.awt.Desktop;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


/**
 *
 * @author carmen
 */
public class FilesPatientWindow extends javax.swing.JFrame {
    public static Patient patient;

    /**
     * Creates new form DoctorInsideWindow
     */
    public FilesPatientWindow() {
        initComponents();
        patient=new Patient();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        DefaultListModel<String> model2 = new DefaultListModel<>();
        JList<String> list = new JList<>(model2);
        String[] Names=new String[100];
        int position=0;
        String nameTaken= "";
        
        for(int i=0;i<PatientInformation.filesNames.length();i++){
            char a = PatientInformation.filesNames.charAt(i);
            while(a != ';'){
                nameTaken = nameTaken + a;
                i++;
                a = PatientInformation.filesNames.charAt(i); 
            }
            
            Names[position]=nameTaken;
            nameTaken="";
            position++;
        }
        for (int i = 0; i < Names.length; i++) {
            if(!Names[i].equals("null")){
                model2.addElement(Names[i]);
            }
        }
        this.ListPatient.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        GoBut = new javax.swing.JButton();
        ExitBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPatient = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("VISUALICE RESULTS:");

        GoBut.setText("Go");
        GoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButActionPerformed(evt);
            }
        });

        ExitBut.setText("Back");
        ExitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButActionPerformed(evt);
            }
        });

        ListPatient.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ListPatient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExitBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GoBut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitBut)
                    .addComponent(GoBut))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButActionPerformed
        ConnectionWithServer.sendSomething(FirstWindow.socket, FirstWindow.printWriter, "e#");
        PatientInformation rd = new PatientInformation();
        this.setVisible(false);
        rd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButActionPerformed

    private void GoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoButActionPerformed
        String line;
        
        try {
            //Check the Patient exist
            File file = new File("files/view.txt");
            if(!file.exists()){
                file.createNewFile();
            }
            String busqueda=this.ListPatient.getSelectedValue();
            ConnectionWithServer.sendSomething(FirstWindow.socket, FirstWindow.printWriter, "s#" + busqueda);
            InputStream inputstream =FirstWindow.socket.getInputStream();
           // public void getFile() {  
		byte[] b=new byte[1024];  
		 try {// Defina la secuencia de entrada,
			InputStream in = FirstWindow.socket.getInputStream();   
			DataInputStream din = new DataInputStream (new BufferedInputStream (in)); // Cree el archivo que se guardará   
			File f = new File("files/view.txt");   
			RandomAccessFile fw = new RandomAccessFile(f, "rw");      
			int num = din.read(b);   
			 while (num != -1) {// Escribe 0 ~ num bytes en el archivo    
				 fw.write (b, 0, num); // Omita los bytes num y vuelva a escribir en el archivo   
				 fw.skipBytes (num); // Leer bytes numéricos    
				num = din.read(b);   
				 } // Cerrar flujo de entrada y salida  
			din.close();   
			fw.close();  
			} catch (Exception e) {   
				e.printStackTrace();  
				}
		//}
            //ObjectInputStream  obj = new ObjectInputStream(inputstream);
           /* try {
                Object d = obj.readObject();
                file = (File) d;
                file.renameTo(new File("file/view.txt"));
                //File dest = new File("files/view.txt");
      //Renaming the file
              /* boolean bool = file.renameTo(dest.getAbsoluteFile());
                // boolean bool = file.renameTo(dest);
                 if(bool) {
                     System.out.println("File moved successfully ........");
                 }else {
                      System.out.println("Unable to move the file ........");
                  }*/
          /*  } catch (ClassNotFoundException ex) {
                Logger.getLogger(FilesPatientWindow.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            Desktop desktop = Desktop.getDesktop();  
            if(file.exists()){ //checks if the file exists or not  
                desktop.open(file); //opens the specified file  
            }
        } catch (IOException ex) {
            Logger.getLogger(FilesPatientWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GoButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilesPatientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilesPatientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilesPatientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilesPatientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilesPatientWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBut;
    private javax.swing.JButton GoBut;
    private javax.swing.JList<String> ListPatient;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
